---
- name: Ensure dependencies installed
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - rsyslog
      - rsyslog-gnutls

- name: Create cert directory
  ansible.builtin.file:
    path: "{{ sumologic_cert_path }}"
    state: directory
    owner: root
    group: root
    mode: 0555

- name: Download Sumo Logic certificate
  ansible.builtin.get_url:
    url: https://www.digicert.com/CACerts/DigiCertHighAssuranceEVRootCA.crt
    dest: "{{ sumologic_cert_path }}/digicert_ca.der"
    owner: root
    group: root
    mode: 0555

- name: Convert cert from DER to PEM format
  ansible.builtin.command: "openssl x509 -inform der -in digicert_ca.der -out {{ sumologic_cert }}"
  args:
    chdir: "{{ sumologic_cert_path }}"
    creates: "{{ sumologic_cert_path }}/{{ sumologic_cert }}"

- name: Install Sumo Logic config
  ansible.builtin.template:
    src: 55-sumologic.conf.j2
    dest: /etc/rsyslog.d/25-sumologic.conf
    owner: root
    group: root
    mode: 0555
  notify: Restart rsyslog
