---
name: ⚛️Molecule testing
on: [push]
jobs:
  molecule-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install test runner
        run: python3 -m pip install tox

      - name: Run tests
        run: tox

        # force color output
        # https://www.jeffgeerling.com/blog/2020/getting-colorized-output-molecule-and-ansible-on-github-actions-ci
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
